version: '3.8'

services:
  desafio_globo_1_carloslopes:
    container_name: desafio_globo_1_carloslopes
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true